import js from "@eslint/js";
import reactPlugin from "eslint-plugin-react";
import tseslint from "typescript-eslint";
import globals from "globals";

export default [
  // 1. Ignore build artifacts and Deno edge functions completely
  {
    ignores: [
      "dist/**",
      "build/**",
      "node_modules/**",
      ".next/**",
      "supabase/**",
      "**/supabase/**",
      "old-ui-code/**",
      "**/old-ui-code/**",
      ".supabase/**",
      "**/.supabase/**",
      // AI Studio design prototype: read-only reference for the Player Experience refactor
      "aktera---gamified-marketing-experience/**",
      // Generated by `npm run test:cov`
      "coverage/**",
    ],
  },

  // 2. Base setups
  js.configs.recommended,
  ...tseslint.configs.recommended,

  // 3. Application rules tuned for MVP prototyping
  {
    files: ["**/*.{js,mjs,cjs,jsx,ts,tsx}"],
    plugins: {
      react: reactPlugin,
    },
    languageOptions: {
      parserOptions: { ecmaFeatures: { jsx: true } },
      globals: { ...globals.browser, ...globals.node },
    },
    settings: {
      react: { version: "detect" },
    },
    rules: {
      // Pull in baseline structures
      ...reactPlugin.configs.flat.recommended.rules,

      // 🛑 STFU Rules — Turning off the annoying micro-management
      "react/react-in-jsx-scope": "off", // Not needed in modern React
      "react/jsx-uses-react": "off", // Not needed in modern React
      "@typescript-eslint/no-explicit-any": "off", // Let me use 'any' when prototyping!
      "react/no-unescaped-entities": "off", // Let me type text/quotes naturally
      "prefer-const": "off", // Don't complain if I used 'let' instead of 'const'

      // ⚠️ Soft Warnings — Highlight but do NOT block builds
      "no-unused-vars": "off", // Handled by TS rule below
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
        },
      ], // Unused variables just show as yellow squiggly lines now

      // ✅ Crucial MVP Checks — Keep these to catch real logical crashes
      "react/jsx-key": "error", // Warns if loops miss a key (breaks UI rendering)
      "no-undef": "error", // Catches real typos in variable names
    },
  },

  // 4. Player Experience module boundaries (see src/features/player-experience/README.md)
  {
    // Outside the module: only its public entry point may be imported.
    files: ["**/*.{js,mjs,cjs,jsx,ts,tsx}"],
    ignores: ["src/features/player-experience/**"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["**/player-experience/*", "!**/player-experience/index"],
              message:
                "Import the Player Experience module through its public entry point (src/features/player-experience/index.ts) only.",
            },
          ],
        },
      ],
    },
  },
  {
    // Inside the runtime: concrete local adapters are injected, never imported.
    files: ["src/features/player-experience/runtime/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["**/services/local", "**/services/local/*"],
              message:
                "The runtime must not import local adapters: receive services through ServicesProvider (useExperienceServices).",
            },
          ],
        },
      ],
    },
  },
  {
    // Inside the domain: pure TypeScript, no UI, no I/O, no upper layer.
    files: ["src/features/player-experience/domain/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: [
                "react",
                "react/*",
                "react-dom",
                "react-dom/*",
                "**/hooks/*",
                "**/contexts/*",
                "**/components/*",
              ],
              message:
                "The domain must stay pure TypeScript: no React and no React-based app code.",
            },
            {
              group: [
                "**/services",
                "**/services/*",
                "**/runtime",
                "**/runtime/*",
                "**/studio",
                "**/studio/*",
              ],
              message:
                "The domain must not import upper layers (services, runtime, studio): they depend on the domain, not the reverse.",
            },
            {
              group: ["lucide-react", "**/presets/icons"],
              message:
                "The domain may read the pure-data presets, but not the icon components (React): use the names in domain/icons.ts.",
            },
            {
              group: ["@supabase/*", "**/lib/supabase"],
              message:
                "The domain must not access Supabase: storage goes through ports in services/.",
            },
          ],
        },
      ],
    },
  },
];
