import { UIProject } from "../types";

/**
 * Downloads a project as a formatted JSON file
 */
export function downloadProjectAsJson(project: UIProject) {
  const dataStr =
    "data:text/json;charset=utf-8," +
    encodeURIComponent(JSON.stringify(project, null, 2));
  const downloadAnchor = document.createElement("a");
  const filename = `${project.name.toLowerCase().replace(/[^a-z0-9]/g, "-")}-ui-project.json`;

  downloadAnchor.setAttribute("href", dataStr);
  downloadAnchor.setAttribute("download", filename);
  document.body.appendChild(downloadAnchor);
  downloadAnchor.click();
  downloadAnchor.remove();
}

/**
 * Parses and validates an imported JSON file
 */
export async function parseImportedProjectFile(file: File): Promise<UIProject> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const content = event.target?.result as string;
        const parsed = JSON.parse(content);

        // Basic schema verification
        if (
          !parsed.screens ||
          !parsed.screens.pregame ||
          !parsed.screens.game
        ) {
          throw new Error("Invalid UI project file: Missing required screens");
        }

        resolve(parsed as UIProject);
      } catch (err: any) {
        reject(new Error(`Failed to parse UIProject JSON: ${err.message}`));
      }
    };
    reader.onerror = () => reject(new Error("Failed to read file"));
    reader.readAsText(file);
  });
}

/**
 * Generates static React + TypeScript code for the project screens
 */
export function generateReactComponentCode(project: UIProject): string {
  return `// Generated by Octoreach Player UI Maker
// Single-file React Runtime with Motion animations

import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';

export type ScreenId = 'pregame' | 'game' | 'lose' | 'win';

export interface GameUIProps {
  initialScreen?: ScreenId;
  data?: {
    'player.health'?: number;
    'player.score'?: string | number;
    'player.name'?: string;
    'player.avatar'?: string;
    [key: string]: any;
  };
  onAction?: (actionName: string, payload?: any) => void;
}

const UI_CONFIG = ${JSON.stringify(project, null, 2)};

export const GamePlayerUI: React.FC<GameUIProps> = ({
  initialScreen = 'pregame',
  data = {},
  onAction,
}) => {
  const [activeScreen, setActiveScreen] = useState<ScreenId>(initialScreen);
  const screen = UI_CONFIG.screens[activeScreen];

  return (
    <div className="relative w-full h-full overflow-hidden select-none bg-[#F0F2F5] text-[#2D3748]">
      <AnimatePresence mode="wait">
        <motion.div
          key={screen.id}
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.3 }}
          className="absolute inset-0 w-full h-full"
          style={{ background: screen.background?.value }}
        >
          {screen.elements.map((el) => {
            const displayVal = (el.binding && data[el.binding] !== undefined)
              ? String(data[el.binding])
              : (el.content || '');

            return (
              <div
                key={el.id}
                style={{
                  position: 'absolute',
                  left: \`\${el.transform.position.x}%\`,
                  top: \`\${el.transform.position.y}%\`,
                  width: \`\${el.transform.size.width}%\`,
                  height: \`\${el.transform.size.height}%\`,
                  transform: \`rotate(\${el.transform.rotation || 0}deg) translate(-50%, -50%)\`,
                  zIndex: el.transform.zIndex || 1,
                  ...el.style,
                }}
              >
                {el.type === 'button' ? (
                  <button
                    onClick={() => onAction?.(el.binding || el.name, displayVal)}
                    className="w-full h-full flex items-center justify-center font-bold"
                  >
                    {displayVal}
                  </button>
                ) : el.type === 'progressBar' ? (
                  <div className="w-full h-full bg-black/40 rounded-full p-0.5">
                    <div
                      className="h-full rounded-full transition-all"
                      style={{
                        width: \`\${Math.min(100, Math.max(0, parseFloat(displayVal) || 100))}%\`,
                        backgroundColor: (el.style?.color as string) || '#10B981',
                      }}
                    />
                  </div>
                ) : (
                  <span>{displayVal}</span>
                )}
              </div>
            );
          })}
        </motion.div>
      </AnimatePresence>
    </div>
  );
};
`;
}
