/**
 * Aktera Multi-Brand Token Engine & Presets
 * 14 Luxury Brand Design Systems tailored for Algerian & Regional B2B campaigns.
 */

export interface AkteraBrandPreset {
  id: string;
  name: string;
  nameAr: string;
  nameFr: string;
  category:
    "luxury" | "retail" | "telecom" | "fmcg" | "auto" | "banking" | "tech";
  logoUrl: string;
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  darkSurface: string;
  lightSurface: string;
  fontFamily: string;
  borderRadius: "sharp" | "rounded" | "pill";
  backgroundType: "solid" | "gradient" | "mesh" | "dots" | "brandImage";
  backgroundValue: string;
  mode?: "dark" | "light";
  sloganFr: string;
  sloganAr: string;
  sloganEn: string;
  prizes: Array<{
    id: string;
    nameFr: string;
    nameAr: string;
    nameEn: string;
    icon: string;
    isWin: boolean;
    color: string;
    value: string;
  }>;
}

export const AKTERA_BRAND_PRESETS: AkteraBrandPreset[] = [
  {
    id: "aktera-gold",
    name: "Aktera Gold Luxe",
    nameFr: "Aktera Gold Luxe",
    nameAr: "أكتيرا جولد لوكس",
    category: "luxury",
    logoUrl:
      "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=120&auto=format&fit=crop&q=80",
    primaryColor: "#F5BA41", // Metallic Gold
    secondaryColor: "#0F172A", // Midnight Slate
    accentColor: "#2563EB", // Royal Blue
    darkSurface: "#0A1120",
    lightSurface: "#FAF8F5",
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    borderRadius: "rounded",
    backgroundType: "mesh",
    backgroundValue:
      "radial-gradient(at 15% 15%, #1e1b4b 0px, transparent 50%), radial-gradient(at 85% 85%, #0f172a 0px, transparent 50%)",
    sloganFr: "Expérience Marketing & Fidélité de Prestige",
    sloganAr: "تجربة التسويق والولاء الفاخرة والمبتكرة",
    sloganEn: "Luxury B2B Gamified Campaign Experience",
    prizes: [
      {
        id: "p1",
        nameFr: "VIP Pass 50 000 DZD",
        nameAr: "بطاقة VIP بقيمة 50,000 دج",
        nameEn: "50,000 DZD VIP Pass",
        icon: "👑",
        isWin: true,
        color: "#F5BA41",
        value: "50 000 DA",
      },
      {
        id: "p2",
        nameFr: "Coffret Cadeau Prestige",
        nameAr: "صندوق هدايا فاخر",
        nameEn: "Prestige Gift Hamper",
        icon: "🎁",
        isWin: true,
        color: "#2563EB",
        value: "Coffret",
      },
      {
        id: "p3",
        nameFr: "Bon d'Achat 10 000 DZD",
        nameAr: "قسيمة شراء 10,000 دج",
        nameEn: "10,000 DZD Voucher",
        icon: "💎",
        isWin: true,
        color: "#10B981",
        value: "10 000 DA",
      },
      {
        id: "p4",
        nameFr: "Chance supplémentaire",
        nameAr: "حظ أوفر المرة القادمة",
        nameEn: "Try Again Next Time",
        icon: "🌙",
        isWin: false,
        color: "#475569",
        value: "0 DA",
      },
    ],
  },
  {
    id: "uno-hypermarche",
    name: "UNO Hypermarché",
    nameFr: "UNO Hypermarché",
    nameAr: "هايبر ماركت أونو",
    category: "retail",
    logoUrl:
      "https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=120&auto=format&fit=crop&q=80",
    primaryColor: "#004FB6", // UNO Blue
    secondaryColor: "#FFCC00", // UNO Yellow
    accentColor: "#E11925", // UNO Red
    darkSurface: "#09142A",
    lightSurface: "#FFFFFF",
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    borderRadius: "rounded",
    backgroundType: "gradient",
    backgroundValue: "#00327A, #001A42",
    sloganFr: "Faites vos courses et gagnez instantanément !",
    sloganAr: "تسوق واربح قسائم شراء فورية !",
    sloganEn: "Shop at UNO & Win Instant Vouchers!",
    prizes: [
      {
        id: "p1",
        nameFr: "Caddie Gratuit 15 000 DA",
        nameAr: "عربة تسوق مجانية 15,000 دج",
        nameEn: "Free Cart 15,000 DZD",
        icon: "🛒",
        isWin: true,
        color: "#FFCC00",
        value: "15 000 DA",
      },
      {
        id: "p2",
        nameFr: "Bon -30% Rayon Électro",
        nameAr: "تخفيض 30% على الأجهزة",
        nameEn: "30% Off Electronics",
        icon: "⚡",
        isWin: true,
        color: "#004FB6",
        value: "-30%",
      },
      {
        id: "p3",
        nameFr: "Bon d'Achat 3 000 DA",
        nameAr: "قسيمة شراء 3,000 دج",
        nameEn: "3,000 DZD Voucher",
        icon: "🎟️",
        isWin: true,
        color: "#E11925",
        value: "3 000 DA",
      },
      {
        id: "p4",
        nameFr: "Rejouez demain",
        nameAr: "حاول غداً مجدداً",
        nameEn: "Try Again Tomorrow",
        icon: "🌟",
        isWin: false,
        color: "#64748B",
        value: "0 DA",
      },
    ],
  },
  {
    id: "ifri-boissons",
    name: "Ifri Eau & Boissons",
    nameFr: "Ifri Eau & Boissons",
    nameAr: "إفـري مياه ومشروبات",
    category: "fmcg",
    logoUrl:
      "https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=120&auto=format&fit=crop&q=80",
    primaryColor: "#00A896", // Pure Spring Cyan
    secondaryColor: "#028090", // Deep Water
    accentColor: "#02C39A", // Mint
    darkSurface: "#041B1C",
    lightSurface: "#F0FDFA",
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    borderRadius: "pill",
    backgroundType: "gradient",
    backgroundValue: "#042F2E, #0F172A",
    sloganFr: "La pureté des montagnes du Djurdjura",
    sloganAr: "نقاء جبال جرجرة مع جوائز الصيف",
    sloganEn: "Pure Mountain Refreshment & Rewards",
    prizes: [
      {
        id: "p1",
        nameFr: "Pack 1 An de Boissons",
        nameAr: "مشروبات مجانية لسنة كاملة",
        nameEn: "1 Year Free Drinks",
        icon: "🥤",
        isWin: true,
        color: "#00A896",
        value: "1 An",
      },
      {
        id: "p2",
        nameFr: "Kit Plage & Glacière Ifri",
        nameAr: "حقيبة بحر وثلاجة إفري",
        nameEn: "Beach Cooler Kit",
        icon: "🏖️",
        isWin: true,
        color: "#02C39A",
        value: "Kit VIP",
      },
      {
        id: "p3",
        nameFr: "Pack Ifri Gazouz & Jus",
        nameAr: "علبة إفري غازوز وعصائر",
        nameEn: "Ifri Gazouz Pack",
        icon: "✨",
        isWin: true,
        color: "#38BDF8",
        value: "Pack",
      },
      {
        id: "p4",
        nameFr: "Merci pour votre participation",
        nameAr: "شكراً على مشاركتك",
        nameEn: "Thank you for playing",
        icon: "💧",
        isWin: false,
        color: "#475569",
        value: "0 DA",
      },
    ],
  },
  {
    id: "djezzy-telecom",
    name: "Djezzy Telecom",
    nameFr: "Djezzy Telecom",
    nameAr: "جيزي للاتصالات",
    category: "telecom",
    logoUrl:
      "https://images.unsplash.com/photo-1512499617640-c74ae3a79d37?w=120&auto=format&fit=crop&q=80",
    primaryColor: "#E10600", // Djezzy Red
    secondaryColor: "#1A1A1A",
    accentColor: "#FFCC00",
    darkSurface: "#1C0505",
    lightSurface: "#FFF5F5",
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    borderRadius: "rounded",
    backgroundType: "mesh",
    backgroundValue:
      "radial-gradient(at 10% 10%, #7f1d1d 0px, transparent 50%), radial-gradient(at 90% 90%, #18181b 0px, transparent 50%)",
    sloganFr: "Vous êtes connectés au meilleur réseau !",
    sloganAr: "أنتم متصلون بأفضل شبكة مع هدايا فورية",
    sloganEn: "Connected to Algeria's Leading Network",
    prizes: [
      {
        id: "p1",
        nameFr: "Pass 50 Go 4G Gratuits",
        nameAr: "اشتراك 50 جيغا 4G مجاناً",
        nameEn: "50 GB 4G Free Pass",
        icon: "🚀",
        isWin: true,
        color: "#E10600",
        value: "50 Go",
      },
      {
        id: "p2",
        nameFr: "Smartphone 5G Récent",
        nameAr: "هاتف ذكي 5G فائق القوة",
        nameEn: "Latest 5G Smartphone",
        icon: "📱",
        isWin: true,
        color: "#FFCC00",
        value: "Smartphone",
      },
      {
        id: "p3",
        nameFr: "Recharge 2 000 DZD",
        nameAr: "رصيد شحن 2,000 دج",
        nameEn: "2,000 DZD Top-up",
        icon: "💳",
        isWin: true,
        color: "#F97316",
        value: "2 000 DA",
      },
      {
        id: "p4",
        nameFr: "Sahhit ! Rejouez demain",
        nameAr: "صحيت! جرب حظك غداً",
        nameEn: "Sahit! Try Tomorrow",
        icon: "🇩🇿",
        isWin: false,
        color: "#52525B",
        value: "0 DA",
      },
    ],
  },
  {
    id: "mobilis-telecom",
    name: "Mobilis 4G/5G",
    nameFr: "Mobilis 4G/5G",
    nameAr: "موبيليس معاً نصنع المستقبل",
    category: "telecom",
    logoUrl:
      "https://images.unsplash.com/photo-1563770660941-20978e870e26?w=120&auto=format&fit=crop&q=80",
    primaryColor: "#009639", // Mobilis Green
    secondaryColor: "#0B2D1B",
    accentColor: "#84CC16",
    darkSurface: "#051C0E",
    lightSurface: "#F0FDF4",
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    borderRadius: "rounded",
    backgroundType: "gradient",
    backgroundValue: "#064E3B, #022C22",
    sloganFr: "Partout avec vous, gagnez avec Mobilis",
    sloganAr: "معاً نصنع المستقبل والجوائز الكبرى",
    sloganEn: "Everywhere with you - Big Prizes",
    prizes: [
      {
        id: "p1",
        nameFr: "Pass Illimité 100 Go",
        nameAr: "اشتراك غير محدود 100 جيغا",
        nameEn: "100 GB Unlimited Pass",
        icon: "⚡",
        isWin: true,
        color: "#009639",
        value: "100 Go",
      },
      {
        id: "p2",
        nameFr: "Tablette 10 Pouces",
        nameAr: "لوحة إلكترونية 10 بوصة",
        nameEn: "10-inch Tablet",
        icon: "💻",
        isWin: true,
        color: "#84CC16",
        value: "Tablette",
      },
      {
        id: "p3",
        nameFr: "Recharge Dima 1 500 DA",
        nameAr: "تعبئة ديما بقيمة 1,500 دج",
        nameEn: "1,500 DA Dima Top-up",
        icon: "🔋",
        isWin: true,
        color: "#10B981",
        value: "1 500 DA",
      },
      {
        id: "p4",
        nameFr: "Bonne chance pour la suite",
        nameAr: "حظ موفق في المرة القادمة",
        nameEn: "Good luck next time",
        icon: "🍀",
        isWin: false,
        color: "#475569",
        value: "0 DA",
      },
    ],
  },
  {
    id: "ooredoo-algerie",
    name: "Ooredoo Algérie",
    nameFr: "Ooredoo Algérie",
    nameAr: "أوريدو عيش التجربة",
    category: "telecom",
    logoUrl:
      "https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?w=120&auto=format&fit=crop&q=80",
    primaryColor: "#ED1C24", // Ooredoo Pure Red
    secondaryColor: "#111827",
    accentColor: "#FFFFFF",
    darkSurface: "#1F0406",
    lightSurface: "#FFFFFF",
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    borderRadius: "pill",
    backgroundType: "dots",
    backgroundValue: "#7F1D1D, #111827",
    sloganFr: "Vivez l'expérience digitale Ooredoo",
    sloganAr: "عش التجربة الرقمية واربح رصيد فوري",
    sloganEn: "Upgrade your world with Ooredoo rewards",
    prizes: [
      {
        id: "p1",
        nameFr: "Pack Switch 60 Go",
        nameAr: "باقة سويتش 60 جيغا",
        nameEn: "Switch 60 GB Pack",
        icon: "📶",
        isWin: true,
        color: "#ED1C24",
        value: "60 Go",
      },
      {
        id: "p2",
        nameFr: "Montre Connectée Pro",
        nameAr: "ساعة ذكية رياضية برو",
        nameEn: "Smart Watch Pro",
        icon: "⌚",
        isWin: true,
        color: "#F43F5E",
        value: "Smartwatch",
      },
      {
        id: "p3",
        nameFr: "Recharge La Switch 1 000 DA",
        nameAr: "رصيد لا سويتش 1,000 دج",
        nameEn: "1,000 DA Top-up",
        icon: "🎁",
        isWin: true,
        color: "#FB7185",
        value: "1 000 DA",
      },
      {
        id: "p4",
        nameFr: "Rejouez pour gagner",
        nameAr: "أعد المحاولة للفوز",
        nameEn: "Play again to win",
        icon: "🌙",
        isWin: false,
        color: "#475569",
        value: "0 DA",
      },
    ],
  },
  {
    id: "cevital-fleurial",
    name: "Cevital / Fleurial",
    nameFr: "Cevital / Fleurial",
    nameAr: "سيفيتال / فلوريال",
    category: "fmcg",
    logoUrl:
      "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=120&auto=format&fit=crop&q=80",
    primaryColor: "#EAB308", // Golden Yellow
    secondaryColor: "#15803D", // Green
    accentColor: "#F97316",
    darkSurface: "#1C1402",
    lightSurface: "#FEFCE8",
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    borderRadius: "rounded",
    backgroundType: "gradient",
    backgroundValue: "#713F12, #1C1917",
    sloganFr: "Le goût de la tradition et de la qualité",
    sloganAr: "جودة المائدة الجزائرية مع هدايا المطبخ",
    sloganEn: "Quality Algerian Kitchen & Cooking Rewards",
    prizes: [
      {
        id: "p1",
        nameFr: "Robot Pâtissier Multifonction",
        nameAr: "عجانة كهربائية متعددة الوظائف",
        nameEn: "Kitchen Stand Mixer",
        icon: "🧁",
        isWin: true,
        color: "#EAB308",
        value: "Robot",
      },
      {
        id: "p2",
        nameFr: "Lot 6 Mois d'Huiles Fleurial",
        nameAr: "مخزون 6 أشهر زيوت فلوريال",
        nameEn: "6 Months Cooking Oil",
        icon: "🌻",
        isWin: true,
        color: "#F97316",
        value: "Pack",
      },
      {
        id: "p3",
        nameFr: "Bon d'Achat Épicerie 5 000 DA",
        nameAr: "قسيمة بقالة 5,000 دج",
        nameEn: "5,000 DA Grocery Voucher",
        icon: "🍳",
        isWin: true,
        color: "#15803D",
        value: "5 000 DA",
      },
      {
        id: "p4",
        nameFr: "Merci pour votre fidélité",
        nameAr: "شكراً لوفائكم الدائم",
        nameEn: "Thank you for your loyalty",
        icon: "❤️",
        isWin: false,
        color: "#57534E",
        value: "0 DA",
      },
    ],
  },
  {
    id: "rouiba-jus",
    name: "Rouiba Jus",
    nameFr: "Rouiba Jus",
    nameAr: "رويبة للعصائر الطبيعية",
    category: "fmcg",
    logoUrl:
      "https://images.unsplash.com/photo-1613478223719-2ab802602423?w=120&auto=format&fit=crop&q=80",
    primaryColor: "#EA580C", // Vibrant Orange
    secondaryColor: "#65A30D", // Lime Green
    accentColor: "#FBBF24",
    darkSurface: "#1C0D02",
    lightSurface: "#FFFBEB",
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    borderRadius: "pill",
    backgroundType: "mesh",
    backgroundValue:
      "radial-gradient(at 15% 15%, #9a3412 0px, transparent 50%), radial-gradient(at 85% 85%, #3f6212 0px, transparent 50%)",
    sloganFr: "Le plein de vitamines et de fraîcheur",
    sloganAr: "طاقة الفواكه الطبيعية وانتعاش فوري",
    sloganEn: "Fresh Natural Fruit Energy & Prizes",
    prizes: [
      {
        id: "p1",
        nameFr: "1 An de Jus Rouiba",
        nameAr: "سنة كاملة من عصائر رويبة",
        nameEn: "1 Year Free Rouiba Juice",
        icon: "🍊",
        isWin: true,
        color: "#EA580C",
        value: "1 An",
      },
      {
        id: "p2",
        nameFr: "Vélo Tout Terrain Sport",
        nameAr: "دراجة جبلية رياضية",
        nameEn: "Sport Mountain Bike",
        icon: "🚴",
        isWin: true,
        color: "#65A30D",
        value: "VTT",
      },
      {
        id: "p3",
        nameFr: "Pack Gourde & Casquette",
        nameAr: "قارورة رياضية وقبعة رويبة",
        nameEn: "Sports Bottle & Cap",
        icon: "🧢",
        isWin: true,
        color: "#FBBF24",
        value: "Goodies",
      },
      {
        id: "p4",
        nameFr: "Encore une chance demain",
        nameAr: "لديك فرصة أخرى غداً",
        nameEn: "Another chance tomorrow",
        icon: "🌟",
        isWin: false,
        color: "#57534E",
        value: "0 DA",
      },
    ],
  },
  {
    id: "yassir-superapp",
    name: "Yassir SuperApp",
    nameFr: "Yassir SuperApp",
    nameAr: "يسير سوبر آب",
    category: "tech",
    logoUrl:
      "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=120&auto=format&fit=crop&q=80",
    primaryColor: "#0D9488", // Yassir Teal
    secondaryColor: "#0F172A",
    accentColor: "#F43F5E",
    darkSurface: "#041B18",
    lightSurface: "#F0FDFA",
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    borderRadius: "rounded",
    backgroundType: "gradient",
    backgroundValue: "#134E4A, #022C22",
    sloganFr: "Vos courses, repas et VTC en un seul clic",
    sloganAr: "تنقل، اطلب طعامك واربح خصومات فورية",
    sloganEn: "On-demand mobility, delivery & instant wins",
    prizes: [
      {
        id: "p1",
        nameFr: "Solde Yassir 20 000 DA",
        nameAr: "رصيد محفظة يسير 20,000 دج",
        nameEn: "20,000 DZD Yassir Pay",
        icon: "💳",
        isWin: true,
        color: "#0D9488",
        value: "20 000 DA",
      },
      {
        id: "p2",
        nameFr: "10 Courses VTC Gratuites",
        nameAr: "10 رحلات مجانية مع يسير",
        nameEn: "10 Free Taxi Rides",
        icon: "🚗",
        isWin: true,
        color: "#F43F5E",
        value: "10 Rides",
      },
      {
        id: "p3",
        nameFr: "Bon Yassir Express 2 000 DA",
        nameAr: "قسيمة طلبات طعام 2,000 دج",
        nameEn: "2,000 DA Food Delivery",
        icon: "🍔",
        isWin: true,
        color: "#06B6D4",
        value: "2 000 DA",
      },
      {
        id: "p4",
        nameFr: "Revenez tenter votre chance",
        nameAr: "عد مجدداً للمحاولة",
        nameEn: "Come back and try again",
        icon: "💫",
        isWin: false,
        color: "#475569",
        value: "0 DA",
      },
    ],
  },
  {
    id: "condor-electronics",
    name: "Condor Electronics",
    nameFr: "Condor Electronics",
    nameAr: "كوندور إلكترونيكس",
    category: "tech",
    logoUrl:
      "https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=120&auto=format&fit=crop&q=80",
    primaryColor: "#2563EB", // Tech Blue
    secondaryColor: "#1E293B",
    accentColor: "#38BDF8",
    darkSurface: "#0B132B",
    lightSurface: "#F8FAFC",
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    borderRadius: "sharp",
    backgroundType: "mesh",
    backgroundValue:
      "radial-gradient(at 10% 10%, #1e40af 0px, transparent 50%), radial-gradient(at 90% 90%, #0f172a 0px, transparent 50%)",
    sloganFr: "L'innovation et la haute technologie algérienne",
    sloganAr: "التكنولوجيا والابتكار الجزائري بجودة عالية",
    sloganEn: "High-tech Algerian Innovation & Smart Devices",
    prizes: [
      {
        id: "p1",
        nameFr: "Smart TV 4K 55 Pouces",
        nameAr: "تلفاز ذكي 55 بوصة 4K",
        nameEn: "55-inch 4K Smart TV",
        icon: "📺",
        isWin: true,
        color: "#2563EB",
        value: 'TV 55"',
      },
      {
        id: "p2",
        nameFr: "Micro-ondes Condor Digital",
        nameAr: "فرن ميكروويف كوندور رقمي",
        nameEn: "Condor Microwave",
        icon: "⚡",
        isWin: true,
        color: "#38BDF8",
        value: "Micro-ondes",
      },
      {
        id: "p3",
        nameFr: "Bon de Réduction -20%",
        nameAr: "قسيمة خصم 20% على الأجهزة",
        nameEn: "20% Discount Voucher",
        icon: "🏷️",
        isWin: true,
        color: "#60A5FA",
        value: "-20%",
      },
      {
        id: "p4",
        nameFr: "Merci pour votre visite",
        nameAr: "شكراً لزيارتكم كوندور",
        nameEn: "Thank you for visiting",
        icon: "🌙",
        isWin: false,
        color: "#64748B",
        value: "0 DA",
      },
    ],
  },
  {
    id: "chery-auto",
    name: "Chery / Geely Auto",
    nameFr: "Chery / Geely Auto",
    nameAr: "شيري / جيلي للسيارات",
    category: "auto",
    logoUrl:
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=120&auto=format&fit=crop&q=80",
    primaryColor: "#DC2626", // Crimson Red
    secondaryColor: "#18181B", // Carbon
    accentColor: "#F59E0B",
    darkSurface: "#1A0808",
    lightSurface: "#FAFAFA",
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    borderRadius: "rounded",
    backgroundType: "gradient",
    backgroundValue: "#7F1D1D, #09090B",
    sloganFr: "Roulez vers l'avenir avec style et puissance",
    sloganAr: "انطلق نحو المستقبل مع أحدث السيارات والجوائز",
    sloganEn: "Drive the Future with Luxury Auto Rewards",
    prizes: [
      {
        id: "p1",
        nameFr: "1 An d'Entretien Gratuit",
        nameAr: "صيانة مجانية لسنة كاملة",
        nameEn: "1 Year Free Maintenance",
        icon: "🛠️",
        isWin: true,
        color: "#DC2626",
        value: "1 An",
      },
      {
        id: "p2",
        nameFr: "Bon Carburant 30 000 DZD",
        nameAr: "بطاقة وقود بقيمة 30,000 دج",
        nameEn: "30,000 DA Fuel Card",
        icon: "⛽",
        isWin: true,
        color: "#F59E0B",
        value: "30 000 DA",
      },
      {
        id: "p3",
        nameFr: "Accessoires Auto Premium",
        nameAr: "إكسسوارات سيارات فاخرة",
        nameEn: "Premium Car Accessories",
        icon: "🚗",
        isWin: true,
        color: "#EA580C",
        value: "Kit Auto",
      },
      {
        id: "p4",
        nameFr: "Prochain tirage bientôt",
        nameAr: "السحب القادم قريباً",
        nameEn: "Next draw coming soon",
        icon: "🏎️",
        isWin: false,
        color: "#52525B",
        value: "0 DA",
      },
    ],
  },
  {
    id: "banque-bna",
    name: "Banque BNA / Gulf",
    nameFr: "Banque BNA / Gulf",
    nameAr: "البنك الوطني الجزائري / الخليج",
    category: "banking",
    logoUrl:
      "https://images.unsplash.com/photo-1541354329998-f4d9a9f9297f?w=120&auto=format&fit=crop&q=80",
    primaryColor: "#0284C7", // Trust Blue
    secondaryColor: "#0F172A",
    accentColor: "#D97706", // Gold
    darkSurface: "#041424",
    lightSurface: "#F0F9FF",
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    borderRadius: "rounded",
    backgroundType: "gradient",
    backgroundValue: "#075985, #020617",
    sloganFr: "Partenaire de vos projets et de votre épargne",
    sloganAr: "شريككم المالي الموثوق نحو النجاح والازدهار",
    sloganEn: "Trusted Banking & Premium Financial Rewards",
    prizes: [
      {
        id: "p1",
        nameFr: "Compte Épargne 100 000 DA",
        nameAr: "حساب توفير بقيمة 100,000 دج",
        nameEn: "100,000 DA Savings Account",
        icon: "💰",
        isWin: true,
        color: "#D97706",
        value: "100 000 DA",
      },
      {
        id: "p2",
        nameFr: "Carte Gold Sans Frais 2 Ans",
        nameAr: "بطاقة جولد مجانية لمدة سنتين",
        nameEn: "Free Gold Card 2 Years",
        icon: "💳",
        isWin: true,
        color: "#0284C7",
        value: "Carte Gold",
      },
      {
        id: "p3",
        nameFr: "Frais de Dossier Offerts",
        nameAr: "إعفاء من مصاريف الملف البنكي",
        nameEn: "Waived Processing Fees",
        icon: "📄",
        isWin: true,
        color: "#38BDF8",
        value: "Offert",
      },
      {
        id: "p4",
        nameFr: "Merci pour votre confiance",
        nameAr: "شكراً لثقتكم الغالية",
        nameEn: "Thank you for your trust",
        icon: "🏛️",
        isWin: false,
        color: "#475569",
        value: "0 DA",
      },
    ],
  },
  {
    id: "aktera-violet",
    name: "Aktera Obsidian Violet",
    nameFr: "Aktera Obsidian Violet",
    nameAr: "أكتيرا البنفسجي الفاخر",
    category: "luxury",
    logoUrl:
      "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=120&auto=format&fit=crop&q=80",
    primaryColor: "#8B5CF6", // Purple Violet
    secondaryColor: "#0B0F19",
    accentColor: "#EC4899", // Fuchsia
    darkSurface: "#0F0B1E",
    lightSurface: "#FAF5FF",
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    borderRadius: "rounded",
    backgroundType: "mesh",
    backgroundValue:
      "radial-gradient(at 15% 15%, #5b21b6 0px, transparent 50%), radial-gradient(at 85% 85%, #831843 0px, transparent 50%)",
    sloganFr: "La puissance de l'engagement gamifié moderne",
    sloganAr: "قوة التفاعل الرقمي والتسويق الحديث",
    sloganEn: "Next-generation gamified engagement",
    prizes: [
      {
        id: "p1",
        nameFr: "Pack VIP Ultra Exclusive",
        nameAr: "باقة VIP الحصرية الكبرى",
        nameEn: "Ultra VIP Exclusive Pack",
        icon: "🔮",
        isWin: true,
        color: "#8B5CF6",
        value: "VIP",
      },
      {
        id: "p2",
        nameFr: "Bon Cadeau 25 000 DZD",
        nameAr: "قسيمة هدية 25,000 دج",
        nameEn: "25,000 DZD Gift Voucher",
        icon: "✨",
        isWin: true,
        color: "#EC4899",
        value: "25 000 DA",
      },
      {
        id: "p3",
        nameFr: "Accès Privilège Membre",
        nameAr: "عضوية مميزة مع هدايا",
        nameEn: "Privilege Member Access",
        icon: "💎",
        isWin: true,
        color: "#A855F7",
        value: "Privilège",
      },
      {
        id: "p4",
        nameFr: "Tentative épuisée",
        nameAr: "انتهت المحاولة الحالية",
        nameEn: "Attempts used",
        icon: "🌙",
        isWin: false,
        color: "#581C87",
        value: "0 DA",
      },
    ],
  },
  {
    id: "clean-light",
    name: "Clean Light Luxe",
    nameFr: "Clean Light Luxe",
    nameAr: "الأبيض الأنيق المعاصر",
    category: "luxury",
    logoUrl:
      "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=120&auto=format&fit=crop&q=80",
    primaryColor: "#2563EB", // Royal Blue
    secondaryColor: "#F1F5F9",
    accentColor: "#F59E0B",
    darkSurface: "#0F172A",
    lightSurface: "#FFFFFF",
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    borderRadius: "rounded",
    backgroundType: "solid",
    backgroundValue: "#FFFFFF",
    sloganFr: "Design épuré et expérience fluide",
    sloganAr: "تصميم نقي وتجربة مستخدم فائقة السلاسة",
    sloganEn: "Minimalist luxury with high conversion",
    prizes: [
      {
        id: "p1",
        nameFr: "Voucher Privilège 15 000 DA",
        nameAr: "قسيمة بريفيليج 15,000 دج",
        nameEn: "15,000 DA Privilege Voucher",
        icon: "🎁",
        isWin: true,
        color: "#2563EB",
        value: "15 000 DA",
      },
      {
        id: "p2",
        nameFr: "Pass Remise -25%",
        nameAr: "بطاقة خصم 25%",
        nameEn: "25% Off Pass",
        icon: "🏷️",
        isWin: true,
        color: "#F59E0B",
        value: "-25%",
      },
      {
        id: "p3",
        nameFr: "Cadeau Surprise Partenaire",
        nameAr: "هدية مفاجأة من الشريك",
        nameEn: "Partner Surprise Gift",
        icon: "🎉",
        isWin: true,
        color: "#10B981",
        value: "Cadeau",
      },
      {
        id: "p4",
        nameFr: "Retentez votre chance",
        nameAr: "حاول مرة أخرى",
        nameEn: "Try your luck again",
        icon: "💫",
        isWin: false,
        color: "#94A3B8",
        value: "0 DA",
      },
    ],
  },
];
