import { GameTemplate } from "../types";

export const DEFAULT_GAME_TEMPLATES: GameTemplate[] = [
  // 1. LUCKY SPIN WHEEL
  {
    id: "lucky_wheel",
    name: "Lucky Spin Wheel",
    description:
      "Instant gratification gamification with visual prize wedges and spinning indicator.",
    slots: [
      {
        slotId: "wheelContainer",
        label: "Spin Wheel Play Zone",
        description: "Center rotating prize wheel with slices and center pin.",
        requiredOnScreens: ["game"],
        allowedTypes: ["panel", "image"],
        lockedFields: ["position", "size"],
        defaultTransform: {
          position: { x: 50, y: 50 },
          size: { width: 55, height: 55 },
          rotation: 0,
          anchor: "center",
          zIndex: 10,
          scaleMode: "preserve-aspect",
        },
        binding: "wheel.spinner",
      },
      {
        slotId: "spinButton",
        label: "Spin Wheel CTA",
        description: "Primary button to trigger wheel spin.",
        requiredOnScreens: ["game"],
        allowedTypes: ["button"],
        lockedFields: ["position"],
        defaultTransform: {
          position: { x: 50, y: 84 },
          size: { width: 28, height: 7.5 },
          rotation: 0,
          anchor: "center",
          zIndex: 15,
          scaleMode: "stretch",
        },
        binding: "wheel.spinAction",
      },
      {
        slotId: "scoreText",
        label: "Score / Attempts Ticker",
        description:
          "Displays current session score or remaining daily attempts.",
        requiredOnScreens: ["game", "win", "lose"],
        allowedTypes: ["text"],
        lockedFields: ["position"],
        defaultTransform: {
          position: { x: 88, y: 4 },
          size: { width: 14, height: 5 },
          rotation: 0,
          anchor: "topRight",
          zIndex: 20,
          scaleMode: "preserve-aspect",
        },
        binding: "player.score",
      },
      {
        slotId: "playButton",
        label: "Start Game Button",
        description: "Entry CTA on pregame screen.",
        requiredOnScreens: ["pregame"],
        allowedTypes: ["button"],
        lockedFields: ["position"],
        defaultTransform: {
          position: { x: 50, y: 76 },
          size: { width: 30, height: 8 },
          rotation: 0,
          anchor: "center",
          zIndex: 15,
          scaleMode: "stretch",
        },
        binding: "game.start",
      },
      {
        slotId: "claimButton",
        label: "Claim Prize Button",
        description: "Prize voucher claim button on victory screen.",
        requiredOnScreens: ["win"],
        allowedTypes: ["button"],
        lockedFields: ["position"],
        defaultTransform: {
          position: { x: 50, y: 74 },
          size: { width: 28, height: 8 },
          rotation: 0,
          anchor: "center",
          zIndex: 15,
          scaleMode: "stretch",
        },
        binding: "prize.claim",
      },
    ],
  },

  // 2. SCRATCH CARD
  {
    id: "scratch_card",
    name: "Scratch Card",
    description: "Digital scratch-to-win card for tactile surprise reveals.",
    slots: [
      {
        slotId: "ticketArea",
        label: "Scratch Ticket Canvas",
        description: "Interactive scratch surface area.",
        requiredOnScreens: ["game"],
        allowedTypes: ["panel", "image"],
        lockedFields: ["position", "size"],
        defaultTransform: {
          position: { x: 50, y: 48 },
          size: { width: 62, height: 48 },
          rotation: 0,
          anchor: "center",
          zIndex: 10,
          scaleMode: "preserve-aspect",
        },
        binding: "scratch.surface",
      },
      {
        slotId: "scratchProgress",
        label: "Scratch Progress Bar",
        description: "Displays percentage revealed.",
        requiredOnScreens: ["game"],
        allowedTypes: ["progressBar"],
        lockedFields: ["position"],
        defaultTransform: {
          position: { x: 50, y: 78 },
          size: { width: 45, height: 3 },
          rotation: 0,
          anchor: "center",
          zIndex: 15,
          scaleMode: "stretch",
        },
        binding: "scratch.progress",
      },
      {
        slotId: "playButton",
        label: "Start Game Button",
        description: "Main CTA on the pregame screen.",
        requiredOnScreens: ["pregame"],
        allowedTypes: ["button"],
        lockedFields: ["position"],
        defaultTransform: {
          position: { x: 50, y: 76 },
          size: { width: 30, height: 8 },
          rotation: 0,
          anchor: "center",
          zIndex: 15,
          scaleMode: "stretch",
        },
        binding: "game.start",
      },
      {
        slotId: "claimButton",
        label: "Claim Prize Button",
        description: "Prize claim button on victory screen.",
        requiredOnScreens: ["win"],
        allowedTypes: ["button"],
        lockedFields: ["position"],
        defaultTransform: {
          position: { x: 50, y: 74 },
          size: { width: 28, height: 8 },
          rotation: 0,
          anchor: "center",
          zIndex: 15,
          scaleMode: "stretch",
        },
        binding: "prize.claim",
      },
    ],
  },

  // 3. MYSTERY BOX
  {
    id: "mystery_box",
    name: "Mystery Box",
    description: "Let users choose one of three boxes to reveal their prize.",
    slots: [
      {
        slotId: "boxesContainer",
        label: "Mystery Boxes Trio",
        description: "Interactive 3-box selection container.",
        requiredOnScreens: ["game"],
        allowedTypes: ["panel"],
        lockedFields: ["position", "size"],
        defaultTransform: {
          position: { x: 50, y: 52 },
          size: { width: 68, height: 35 },
          rotation: 0,
          anchor: "center",
          zIndex: 10,
          scaleMode: "preserve-aspect",
        },
        binding: "mystery.boxes",
      },
      {
        slotId: "instructionText",
        label: "Pick a Box Prompt",
        description: "Instruction text prompting the player to tap a box.",
        requiredOnScreens: ["game"],
        allowedTypes: ["text"],
        lockedFields: ["position"],
        defaultTransform: {
          position: { x: 50, y: 28 },
          size: { width: 50, height: 6 },
          rotation: 0,
          anchor: "center",
          zIndex: 15,
          scaleMode: "stretch",
        },
        binding: "mystery.prompt",
      },
      {
        slotId: "playButton",
        label: "Start Game Button",
        description: "Main CTA on the pregame screen.",
        requiredOnScreens: ["pregame"],
        allowedTypes: ["button"],
        lockedFields: ["position"],
        defaultTransform: {
          position: { x: 50, y: 76 },
          size: { width: 30, height: 8 },
          rotation: 0,
          anchor: "center",
          zIndex: 15,
          scaleMode: "stretch",
        },
        binding: "game.start",
      },
      {
        slotId: "claimButton",
        label: "Claim Prize CTA",
        description: "Reward claim button on win screen.",
        requiredOnScreens: ["win"],
        allowedTypes: ["button"],
        lockedFields: ["position"],
        defaultTransform: {
          position: { x: 50, y: 74 },
          size: { width: 28, height: 8 },
          rotation: 0,
          anchor: "center",
          zIndex: 15,
          scaleMode: "stretch",
        },
        binding: "prize.claim",
      },
    ],
  },

  // 4. HIT IT REACTION GAME
  {
    id: "hit_it",
    name: "Hit It Reaction Game",
    description: "Fast-paced target tapping game against a countdown timer.",
    slots: [
      {
        slotId: "hitTargetArea",
        label: "Reaction Target Field",
        description: "Interactive tapping area where moving target appears.",
        requiredOnScreens: ["game"],
        allowedTypes: ["panel"],
        lockedFields: ["position", "size"],
        defaultTransform: {
          position: { x: 50, y: 52 },
          size: { width: 68, height: 50 },
          rotation: 0,
          anchor: "center",
          zIndex: 10,
          scaleMode: "preserve-aspect",
        },
        binding: "hitit.targetArea",
      },
      {
        slotId: "timerBar",
        label: "Countdown Timer Bar",
        description: "Visual timer showing remaining reaction seconds.",
        requiredOnScreens: ["game"],
        allowedTypes: ["progressBar"],
        lockedFields: ["position"],
        defaultTransform: {
          position: { x: 50, y: 12 },
          size: { width: 50, height: 3 },
          rotation: 0,
          anchor: "center",
          zIndex: 15,
          scaleMode: "stretch",
        },
        binding: "game.timer",
      },
      {
        slotId: "scoreText",
        label: "Hit Counter",
        description: "Displays current successful hit count.",
        requiredOnScreens: ["game", "win", "lose"],
        allowedTypes: ["text"],
        lockedFields: ["position"],
        defaultTransform: {
          position: { x: 88, y: 4 },
          size: { width: 14, height: 5 },
          rotation: 0,
          anchor: "topRight",
          zIndex: 20,
          scaleMode: "preserve-aspect",
        },
        binding: "player.score",
      },
      {
        slotId: "playButton",
        label: "Start Challenge Button",
        description: "Main CTA on the pregame screen.",
        requiredOnScreens: ["pregame"],
        allowedTypes: ["button"],
        lockedFields: ["position"],
        defaultTransform: {
          position: { x: 50, y: 76 },
          size: { width: 30, height: 8 },
          rotation: 0,
          anchor: "center",
          zIndex: 15,
          scaleMode: "stretch",
        },
        binding: "game.start",
      },
      {
        slotId: "claimButton",
        label: "Claim Prize Button",
        description: "Prize claim button on victory screen.",
        requiredOnScreens: ["win"],
        allowedTypes: ["button"],
        lockedFields: ["position"],
        defaultTransform: {
          position: { x: 50, y: 74 },
          size: { width: 28, height: 8 },
          rotation: 0,
          anchor: "center",
          zIndex: 15,
          scaleMode: "stretch",
        },
        binding: "prize.claim",
      },
    ],
  },

  // 5. TRIVIA QUIZ CHALLENGE
  {
    id: "quiz",
    name: "Trivia Quiz Challenge",
    description: "Skill & knowledge based entry before claiming rewards.",
    slots: [
      {
        slotId: "questionPanel",
        label: "Question Prompt Card",
        description: "Main card showing trivia question and options.",
        requiredOnScreens: ["game"],
        allowedTypes: ["panel", "text"],
        lockedFields: ["position"],
        defaultTransform: {
          position: { x: 50, y: 45 },
          size: { width: 68, height: 42 },
          rotation: 0,
          anchor: "center",
          zIndex: 10,
          scaleMode: "stretch",
        },
        binding: "quiz.question",
      },
      {
        slotId: "timerBar",
        label: "Quiz Countdown Bar",
        description: "Visual timer showing remaining seconds.",
        requiredOnScreens: ["game"],
        allowedTypes: ["progressBar"],
        lockedFields: ["position"],
        defaultTransform: {
          position: { x: 50, y: 10 },
          size: { width: 55, height: 2.5 },
          rotation: 0,
          anchor: "center",
          zIndex: 15,
          scaleMode: "stretch",
        },
        binding: "quiz.timer",
      },
      {
        slotId: "playButton",
        label: "Start Quiz Button",
        description: "Main CTA on the pregame screen.",
        requiredOnScreens: ["pregame"],
        allowedTypes: ["button"],
        lockedFields: ["position"],
        defaultTransform: {
          position: { x: 50, y: 76 },
          size: { width: 30, height: 8 },
          rotation: 0,
          anchor: "center",
          zIndex: 15,
          scaleMode: "stretch",
        },
        binding: "game.start",
      },
      {
        slotId: "claimButton",
        label: "Claim Prize Button",
        description: "Prize claim button on victory screen.",
        requiredOnScreens: ["win"],
        allowedTypes: ["button"],
        lockedFields: ["position"],
        defaultTransform: {
          position: { x: 50, y: 74 },
          size: { width: 28, height: 8 },
          rotation: 0,
          anchor: "center",
          zIndex: 15,
          scaleMode: "stretch",
        },
        binding: "prize.claim",
      },
    ],
  },
];

export function getGameTemplateById(id: string): GameTemplate {
  return (
    DEFAULT_GAME_TEMPLATES.find((t) => t.id === id) || DEFAULT_GAME_TEMPLATES[0]
  );
}

export function getGameTemplateByGameType(gameType?: string): GameTemplate {
  if (!gameType) return DEFAULT_GAME_TEMPLATES[0];
  const matched = DEFAULT_GAME_TEMPLATES.find(
    (t) => t.id === gameType || t.id.toLowerCase() === gameType.toLowerCase(),
  );
  return matched || DEFAULT_GAME_TEMPLATES[0];
}
