import { Campaign, PrizeTemplate, LeadEntry } from "./types";

export const INITIAL_PRIZES: PrizeTemplate[] = [
  {
    id: "pass_10gb",
    name: "10 GB Flexy Pass",
    category: "voucher",
    description:
      "Instant 10GB mobile internet pass redeemable on any prepaid line.",
    totalStock: 5000,
    availableStock: 2450,
    allocatedStock: 2550,
    itemValue: "1000 DA",
  },
  {
    id: "credit_100da",
    name: "100 DA Flexy Credit",
    category: "voucher",
    description: "100 DA calling and SMS credit transfer.",
    totalStock: 10000,
    availableStock: 8200,
    allocatedStock: 1800,
    itemValue: "100 DA",
  },
  {
    id: "yassir_ride_20",
    name: "Yassir Ride -20%",
    category: "voucher",
    description:
      "Discount coupon for urban transport services via Yassir Taxi.",
    totalStock: 3000,
    availableStock: 1100,
    allocatedStock: 1900,
    itemValue: "250 DA",
  },
  {
    id: "hamoud_cap",
    name: "Classic Vintage Hamoud Cap",
    category: "physical",
    description: "Premium branded cap with customized embroidery.",
    totalStock: 150,
    availableStock: 34,
    allocatedStock: 116,
    itemValue: "1800 DA",
  },
  {
    id: "soummam_basket",
    name: "Soummam Dairy Gift Basket",
    category: "physical",
    description:
      "Nutritious package with organic yogurts, fresh cream, and standard cutlery.",
    totalStock: 100,
    availableStock: 12,
    allocatedStock: 88,
    itemValue: "3500 DA",
  },
  {
    id: "yassir_food_40",
    name: "Yassir Food -40%",
    category: "voucher",
    description:
      "Super discount on food delivery partners across Algiers & Oran.",
    totalStock: 2500,
    availableStock: 1420,
    allocatedStock: 1080,
    itemValue: "600 DA",
  },
];

export const INITIAL_CAMPAIGNS: Campaign[] = [
  {
    id: "camp_djezzy_ramadan_2026",
    name: "Zid l'Heure Ramadan Wheel",
    arabicName: "تحدي زيد الهدرة لرمضان 🌙",
    slug: "djezzy-ramadan-2026",
    gameType: "lucky_wheel",
    status: "active",
    winProbability: 65,
    prizes: [
      { templateId: "pass_10gb", quantity: 2000, weight: 30 },
      { templateId: "credit_100da", quantity: 1500, weight: 50 },
      { templateId: "yassir_ride_20", quantity: 1000, weight: 20 },
    ],
    questions: [],
    participantsCount: 4520,
    rewardsClaimed: 2938,
    startDate: "2026-03-01",
    endDate: "2026-04-05",
  },
  {
    id: "camp_yassir_express_fast",
    name: "Grand Yassir Express Delivery Challenge",
    arabicName: "عجلة الحظ الكبرى ليسير إكسبريس 🚕",
    slug: "yassir-express-2026",
    gameType: "lucky_wheel",
    status: "active",
    winProbability: 40,
    prizes: [
      { templateId: "yassir_ride_20", quantity: 900, weight: 40 },
      { templateId: "yassir_food_40", quantity: 1080, weight: 60 },
    ],
    questions: [],
    participantsCount: 3120,
    rewardsClaimed: 1248,
    startDate: "2026-04-10",
    endDate: "2026-05-15",
  },
  {
    id: "camp_hamoud_shour_refresh",
    name: "S'hour Win & Refresh Quiz",
    arabicName: "مسابقة الانتعاش مع حمود بوعلام 🍾",
    slug: "hamoud-shour-quiz",
    gameType: "quiz",
    status: "paused",
    winProbability: 50,
    prizes: [{ templateId: "hamoud_cap", quantity: 116, weight: 100 }],
    questions: [
      {
        id: "q1",
        questionText: "When was Hamoud Boualem founded in Algiers?",
        options: ["1878", "1954", "1962", "1905"],
        correctIndex: 0,
      },
      {
        id: "q2",
        questionText: "What is the signature white soda bottle flavor called?",
        options: ["Slim Lemon", "Hamoud Select", "Slim Apple", "Rouiba Orange"],
        correctIndex: 1,
      },
    ],
    participantsCount: 1840,
    rewardsClaimed: 920,
    startDate: "2026-05-20",
    endDate: "2026-06-25",
  },
  {
    id: "camp_soummam_smile_daily",
    name: "Daily Healthy Smile Campaign",
    arabicName: "ابتسامتك اليومية مع صومام 🍓",
    slug: "soummam-smile-2026",
    gameType: "lucky_wheel",
    status: "draft",
    winProbability: 80,
    prizes: [{ templateId: "soummam_basket", quantity: 88, weight: 100 }],
    questions: [],
    participantsCount: 0,
    rewardsClaimed: 0,
    startDate: "2026-07-10",
    endDate: "2026-08-10",
  },
];

export const INITIAL_LEADS: LeadEntry[] = [
  {
    id: "lead_1",
    campaignId: "camp_djezzy_ramadan_2026",
    campaignName: "Zid l'Heure Ramadan Wheel",
    playerName: "Anis Belkacem",
    phoneNumber: "0550123456",
    prizeWon: "10 GB Flexy Pass",
    timestamp: "2026-07-04 11:24",
    consentGiven: true,
    couponCode: "DJZ-10GB-FLX99",
    status: "confirmed",
  },
  {
    id: "lead_2",
    campaignId: "camp_djezzy_ramadan_2026",
    campaignName: "Zid l'Heure Ramadan Wheel",
    playerName: "Meriem Haddad",
    phoneNumber: "0661987654",
    prizeWon: "100 DA Flexy Credit",
    timestamp: "2026-07-04 12:05",
    consentGiven: true,
    couponCode: "DJZ-CRD-100DZD",
    status: "confirmed",
  },
  {
    id: "lead_3",
    campaignId: "camp_yassir_express_fast",
    campaignName: "Grand Yassir Express Delivery Challenge",
    playerName: "Fateh Benzahra",
    phoneNumber: "0772456123",
    prizeWon: "Yassir Food -40%",
    timestamp: "2026-07-04 12:45",
    consentGiven: true,
    couponCode: "YSR-FOOD-DISC40",
    status: "pending",
  },
  {
    id: "lead_4",
    campaignId: "camp_hamoud_shour_refresh",
    campaignName: "S'hour Win & Refresh Quiz",
    playerName: "Yasmin Saadi",
    phoneNumber: "0560778899",
    prizeWon: "Classic Vintage Hamoud Cap",
    timestamp: "2026-07-04 13:01",
    consentGiven: true,
    couponCode: "HMD-CAP-MERCH88",
    status: "confirmed",
  },
  {
    id: "lead_5",
    campaignId: "camp_yassir_express_fast",
    campaignName: "Grand Yassir Express Delivery Challenge",
    playerName: "Sidali Rezgui",
    phoneNumber: "0799334455",
    prizeWon: "Better Luck Next Time",
    timestamp: "2026-07-04 13:12",
    consentGiven: true,
    status: "confirmed",
  },
];
